apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: frontend-karsajob
spec:
  type: NodePort
  selector:
    app: frontend-karsajob
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
