apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: backend-karsajob
spec:
  type: NodePort
  selector:
    app: backend-karsajob
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
