apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-karsajob
  template:
    metadata:
      labels:
        app: backend-karsajob
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/imamlabs/karsajobs:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo-service"  # Menggunakan nama service MongoDB
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
