version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  node: circleci/node@4.0.0

jobs:
  lint-dockerfile:
    executor:
      name: docker/default
      tag: '19.03'
    steps:
      - checkout
      - setup_remote_docker:  # Mengaktifkan Docker pada lingkungan eksekusi
          version: 19.03.13  # Versi Docker yang diinginkan
      - run:
          name: Lint Dockerfile
          command: docker run --rm -i hadolint/hadolint < Dockerfile

  build-app-karsajobs-ui:
    executor: docker/default
    steps:
      - checkout
      - run:
          name: Build and Push karsajobs-ui Image
          command: |
            docker build -t ghcr.io/imamlabs/karsajobs-ui:latest .
            echo "${DOCKER_PASSWORD}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
            docker push ghcr.io/imamlabs/karsajobs-ui:latest

workflows:
  ci:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
