version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3

jobs:
  test-app:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker/docker
    environment:
      DOCKER_USERNAME: imamlabs
      DOCKER_PASSWORD: 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
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push karsajobs Image
          command: |
            DOCKER_IMAGE_TAG=$(git rev-parse --short HEAD)
            docker build -t ghcr.io/$DOCKER_USERNAME/karsajobs:$DOCKER_IMAGE_TAG .
            echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
            docker push ghcr.io/$DOCKER_USERNAME/karsajobs:$DOCKER_IMAGE_TAG


workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - test-app
      - build-app-karsajobs:
          requires:
            - docker/hadolint
            - test-app
