version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  node: circleci/node@4.0.0

jobs:
  lint-dockerfile:
    docker:
      - image: 'cimg/base:2022.01'
    steps:
      - checkout
      - run:
          name: Install and Run Hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
            hadolint Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: 'cimg/base:2022.01'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push karsajobs-ui Image
          command: |
         
            echo "Build karsajobs-ui"
            echo "${DOCKER_PASSWORD}" | docker login ghcr.io -u "${DOCKER_USERNAME}" --password-stdin
            docker build -t ghcr.io/$DOCKER_USERNAME/karsajobs-ui:latest -f Dockerfile .
            docker push ghcr.io/$DOCKER_USERNAME/karsajobs-ui:latest

workflows:
  ci:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
