version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3

jobs:
  test-app:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker/docker
    environment:
      DOCKER_USERNAME: imamlabs
      DOCKER_PASSWORD: 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
    steps:
      - checkout
      - run:
          name: Logout from Docker
          command: |
            docker logout
          when: always  # Menjamin langkah ini dijalankan bahkan jika langkah selanjutnya gagal
      - setup_remote_docker
      - run:
          name: Test login
          command: |
            echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - test-app
      - build-app-karsajobs:
          requires:
            - docker/hadolint
            - test-app
