version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3

jobs:
  test-app:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - run:
          name: Run Unit Test
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker/docker
    environment:
      DOCKER_USERNAME: imamlabs
      DOCKER_PASSWORD: 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
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push karsajobs Image
          command: |
            docker build -t ghcr.io/$DOCKER_USERNAME/karsajobs:latest -f Dockerfile .
            echo "$DOCKER_PASSWORD" | docker login ghcr.io -u "$DOCKER_USERNAME" --password-stdin
            docker push ghcr.io/$DOCKER_USERNAME/karsajobs:latest

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - test-app
      - build-app-karsajobs:
          requires:
            - docker/hadolint
            - test-app
